apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secret
  namespace: shopkube
type: Opaque
data:
  DB_PASSWORD: c2hvcGt1YmVfcGFzcw==
  RABBITMQ_URL: YW1xcDovL3Nob3BrdWJlOnNob3BrdWJlX3Bhc3NAcmFiYml0bXE6NTY3Mi8=
