apiVersion: v1
kind: Secret
metadata:
  name: inventory-service-secret
  namespace: shopkube
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9zaG9wa3ViZTpzaG9wa3ViZV9wYXNzQHBvc3RncmVzOjU0MzIvc2hvcGt1YmU=
