apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secret
  namespace: shopkube
type: Opaque
data:
  RABBITMQ_URL: YW1xcDovL3Nob3BrdWJlOnNob3BrdWJlX3Bhc3NAcmFiYml0bXE6NTY3Mi8=
  CELERY_BROKER_URL: YW1xcDovL3Nob3BrdWJlOnNob3BrdWJlX3Bhc3NAcmFiYml0bXE6NTY3Mi8=
