apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: shopkube
type: Opaque
data:
  POSTGRES_DB: c2hvcGt1YmU=
  POSTGRES_USER: c2hvcGt1YmU=
  POSTGRES_PASSWORD: c2hvcGt1YmVfcGFzcw==
