apiVersion: v1
kind: Secret
metadata:
  name: review-service-secret
  namespace: shopkube
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Nob3BrdWJlOnNob3BrdWJlX3Bhc3NAcG9zdGdyZXM6NTQzMi9zaG9wa3ViZV9yZXZpZXdz
  SECRET_KEY_BASE: Y2hhbmdlbWUtc2VjcmV0LWtleS1iYXNlLW1pbmltdW0tMzItY2hhcnM=
