apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  namespace: shopkube
data:
  PORT: "8082"
  MONGODB_URL: "mongodb://mongodb:27017"
  MONGODB_DB: "shopkube"
  LOG_LEVEL: "info"
