apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: shopkube
data:
  PORT: "8081"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "shopkube"
  DB_USER: "shopkube"
  LOG_LEVEL: "info"
