apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: shopkube
  labels:
    app: inventory-service
spec:
  type: ClusterIP
  selector:
    app: inventory-service
  ports:
    - port: 8086
      targetPort: 8086
      protocol: TCP
